#!/usr/bin/env bash
# Generated by ralph — re-running scaffold overwrites this file.
set -euo pipefail

# Install the AI CLI
npm install -g @anthropic-ai/claude-code

# Fix ownership of named volumes (Docker creates them as root, container runs as the dev user)
sudo chown -R node:node /home/node/.claude /home/node/.config/gh

# Install RTK (commit-pinned to prevent supply-chain risk from a mutable branch ref)
# echo "n" answers the interactive telemetry prompt; rtk telemetry disable is belt-and-suspenders
curl -fsSL https://raw.githubusercontent.com/rtk-ai/rtk/80a6fe606f73b19e52b0b330d242e62a6c07be42/install.sh -o /tmp/rtk-install.sh
echo "n" | sh /tmp/rtk-install.sh
rtk telemetry disable

# Initialize RTK for this CLI
rtk init -g

# Install the Caveman plugin (guarded so a rebuilt volume skips re-install)
[ -d "$HOME/.claude/plugins/caveman" ] || (claude plugin marketplace add JuliusBrussee/caveman && claude plugin install caveman@caveman)

# Clone awesome-claude-code-subagents (guarded so a rebuilt volume skips re-clone)
[ -d "$HOME/.claude/agents/awesome-subagents" ] || (mkdir -p "$HOME/.claude/agents" && git clone --depth=1 https://github.com/VoltAgent/awesome-claude-code-subagents "$HOME/.claude/agents/awesome-subagents")

# Remove the VS Code credential helper injected at container build time
git config --global --unset-all credential.helper || true
