#!/usr/bin/env bash
# Generated by ralph — re-running scaffold overwrites this file.
set -euo pipefail

WORKSPACE_FOLDER="${1:?containerWorkspaceFolder argument required}"

# Clear VS Code git credential forwarders that re-inject on each container start
unset VSCODE_GIT_IPC_HANDLE GIT_ASKPASS VSCODE_GIT_ASKPASS_NODE VSCODE_GIT_ASKPASS_MAIN

# Remove credential helper added by VS Code
git config --global --unset-all credential.helper || true

# Authenticate gh CLI with the project-scoped PAT
gh auth login --with-token < "${WORKSPACE_FOLDER}/.ralph/token"
gh auth setup-git
